### ISSUE TITLE
Redirecting people to my fork.

### ISSUE THREAD

**Issue by BigBrainAFK** [AymanDev/YouTube-Music-Client#2]
So I have looked for a YT Music Client for quiet a while. I am very happy to have found this although I was a bit disappointed that this hasn't moved in 7 months. I made quiet a few changes in my fork of this including: getting tile info from YT Musics own title info at the bottom, auto-updating, smaller changes to the presence, and a checker that should reconnect the RPC if another program takes over and gets closed.

**Comment by AymanDev** [comment]
Made it in commit https://github.com/AymanDev/YouTube-Music-Client/commit/2b7ec436563bd79f38be376b86248a63207fefa4
